const AT = {
  SET_TEXT_SYNC: 'SET_TEXT_SYNC',
  SET_TEXT_ASYNC: 'SET_TEXT_ASYNC',
  SET_TEXT_ASYNC_SUCCESS: 'SET_TEXT_ASYNC_SUCCESS',
  SET_TEXT_ASYNC_FAIL: 'SET_TEXT_ASYNC_FAIL'
};

export default AT;
